{"name": "test_mul_004", "status": "failed", "statusDetails": {"message": "AssertionError: assert False", "trace": "self = <test_005.Test_Credence_005 object at 0x000001FFDC848790>\n\n    def test_mul_004(self):\n        a = 3\n        b = 7\n        mul = a * b\n        print(\"Mul of a and b is :\" + str(mul))\n        if mul == 10:\n            assert True\n        else:\n>           assert False\nE           assert False\n\ntest_005.py:11: AssertionError"}, "start": 1690662657925, "stop": 1690662657925, "uuid": "efb4e1d7-c6ca-43a9-ae71-9d0d74545324", "historyId": "ec34f55bfa501d7ee5b0c1c9d663c8a9", "testCaseId": "ec34f55bfa501d7ee5b0c1c9d663c8a9", "fullName": "test_005.Test_Credence_005#test_mul_004", "labels": [{"name": "suite", "value": "test_005"}, {"name": "subSuite", "value": "Test_Credence_005"}, {"name": "host", "value": "LAPTOP-0UVS3GMM"}, {"name": "thread", "value": "3288-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_005"}]}